language: node_js

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: npm test
      node_js:
        - "8"
      cache: npm
      services:
        - docker
      install:
        - npm install
      before_script:
        - npm run lint
      script:
        - npm run test

    - stage: npm release
      if: tag IS present
      node_js: "8"
      cache: npm
      script: npm install
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
